//
// Created by zwm on 2020/7/4.
//

#ifndef HIATPG_LOGICVALUE_H
#define HIATPG_LOGICVALUE_H
#include "model.h"
static vector<Value> simAnd{
    X,     ZERO,  X,     UNDEF, ZERO,  ZERO,  ZERO,  UNDEF, X,     ZERO,  X,     UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    ZERO,  ZERO,  ZERO,  UNDEF, ZERO,  ZERO,  ZERO,  UNDEF, ZERO,  ZERO,  ZERO,  UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    X,     ZERO,  X,     UNDEF, ZERO,  ZERO,  ZERO,  UNDEF, X,     ZERO,  X,     UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    ZERO,  ZERO,  ZERO,  UNDEF, ZERO,  ZERO,  ZERO,  UNDEF, ZERO,  ZERO,  ZERO,  UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    ZERO,  ZERO,  ZERO,  UNDEF, ZERO,  ZERO,  ZERO,  UNDEF, ZERO,  ZERO,  ZERO,  UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    ZERO,  ZERO,  ZERO,  UNDEF, ZERO,  ZERO,  ZERO,  UNDEF, ZERO,  ZERO,  ZERO,  UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    X,     ZERO,  X,     UNDEF, ZERO,  ZERO,  ZERO,  UNDEF, X,     ZERO,  X,     UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    ZERO,  ZERO,  ZERO,  UNDEF, ZERO,  ZERO,  ZERO,  UNDEF, ZERO,  ZERO,  ZERO,  UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    X,     ZERO,  X,     UNDEF, ZERO,  ZERO,  ZERO,  UNDEF, X,     ZERO,  ONE,   UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF};
static vector<Value> simNand{
    X,     ONE,   X,     UNDEF, ONE,   ONE,   ONE,   UNDEF, X,     ONE,   X,     UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    ONE,   ONE,   ONE,   UNDEF, ONE,   ONE,   ONE,   UNDEF, ONE,   ONE,   ONE,   UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    X,     ONE,   X,     UNDEF, ONE,   ONE,   ONE,   UNDEF, X,     ONE,   X,     UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    ONE,   ONE,   ONE,   UNDEF, ONE,   ONE,   ONE,   UNDEF, ONE,   ONE,   ONE,   UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    ONE,   ONE,   ONE,   UNDEF, ONE,   ONE,   ONE,   UNDEF, ONE,   ONE,   ONE,   UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    ONE,   ONE,   ONE,   UNDEF, ONE,   ONE,   ONE,   UNDEF, ONE,   ONE,   ONE,   UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    X,     ONE,   X,     UNDEF, ONE,   ONE,   ONE,   UNDEF, X,     ONE,   X,     UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    ONE,   ONE,   ONE,   UNDEF, ONE,   ONE,   ONE,   UNDEF, ONE,   ONE,   ONE,   UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    X,     ONE,   X,     UNDEF, ONE,   ONE,   ONE,   UNDEF, X,     ONE,   ZERO,  UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF};
static vector<Value> simOr{
    X,     X,     ONE,   UNDEF, X,     X,     ONE,   UNDEF, ONE,   ONE,   ONE,   UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    X,     X,     ONE,   UNDEF, X,     X,     ONE,   UNDEF, ONE,   ONE,   ONE,   UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    ONE,   ONE,   ONE,   UNDEF, ONE,   ONE,   ONE,   UNDEF, ONE,   ONE,   ONE,   UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    X,     X,     ONE,   UNDEF, X,     X,     ONE,   UNDEF, ONE,   ONE,   ONE,   UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    X,     X,     ONE,   UNDEF, X,     ZERO,  ONE,   UNDEF, ONE,   ONE,   ONE,   UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    ONE,   ONE,   ONE,   UNDEF, ONE,   ONE,   ONE,   UNDEF, ONE,   ONE,   ONE,   UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    ONE,   ONE,   ONE,   UNDEF, ONE,   ONE,   ONE,   UNDEF, ONE,   ONE,   ONE,   UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    ONE,   ONE,   ONE,   UNDEF, ONE,   ONE,   ONE,   UNDEF, ONE,   ONE,   ONE,   UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    ONE,   ONE,   ONE,   UNDEF, ONE,   ONE,   ONE,   UNDEF, ONE,   ONE,   ONE,   UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF};

static vector<Value> simNor{
    X,     X,     ZERO,  UNDEF, X,     X,     ZERO,  UNDEF, ZERO,  ZERO,  ZERO,  UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    X,     X,     ZERO,  UNDEF, X,     X,     ZERO,  UNDEF, ZERO,  ZERO,  ZERO,  UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    ZERO,  ZERO,  ZERO,  UNDEF, ZERO,  ZERO,  ZERO,  UNDEF, ZERO,  ZERO,  ZERO,  UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    X,     X,     ZERO,  UNDEF, X,     X,     ZERO,  UNDEF, ZERO,  ZERO,  ZERO,  UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    X,     X,     ZERO,  UNDEF, X,     ONE,   ZERO,  UNDEF, ZERO,  ZERO,  ZERO,  UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    ZERO,  ZERO,  ZERO,  UNDEF, ZERO,  ZERO,  ZERO,  UNDEF, ZERO,  ZERO,  ZERO,  UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    ZERO,  ZERO,  ZERO,  UNDEF, ZERO,  ZERO,  ZERO,  UNDEF, ZERO,  ZERO,  ZERO,  UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    ZERO,  ZERO,  ZERO,  UNDEF, ZERO,  ZERO,  ZERO,  UNDEF, ZERO,  ZERO,  ZERO,  UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    ZERO,  ZERO,  ZERO,  UNDEF, ZERO,  ZERO,  ZERO,  UNDEF, ZERO,  ZERO,  ZERO,  UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF,
    UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF};

static vector<Value> simXor{X, X, X, UNDEF, X, ZERO, ONE, UNDEF, X, ONE, ZERO, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF};
static vector<Value> simXnor{X, X, X, UNDEF, X, ONE, ZERO, UNDEF, X, ZERO, ONE, UNDEF, UNDEF, UNDEF, UNDEF, UNDEF};
static vector<Value> simInv{X, ONE, ZERO, UNDEF};
static vector<Value> simBuf{X, ZERO, ONE, UNDEF};

#endif  // HIATPG_LOGICVALUE_H
