list(APPEND HEADERS ${CMAKE_CURRENT_LIST_DIR}/ATPGDriver.h)
list(APPEND SOURCES ${CMAKE_CURRENT_LIST_DIR}/ATPGDriver.cpp)

list(APPEND HEADERS ${CMAKE_CURRENT_LIST_DIR}/ATPGDriverDefault.h)
list(APPEND SOURCES ${CMAKE_CURRENT_LIST_DIR}/ATPGDriverDefault.cpp)

list(APPEND HEADERS ${CMAKE_CURRENT_LIST_DIR}/CubeGenerator.h)
list(APPEND SOURCES ${CMAKE_CURRENT_LIST_DIR}/CubeGenerator.cpp)

list(APPEND HEADERS ${CMAKE_CURRENT_LIST_DIR}/CubeGeneratorExample.h)
list(APPEND SOURCES ${CMAKE_CURRENT_LIST_DIR}/CubeGeneratorExample.cpp)
