list(APPEND HEADERS ${CMAKE_CURRENT_LIST_DIR}/Gate.h)
list(APPEND SOURCES ${CMAKE_CURRENT_LIST_DIR}/Gate.cpp)

list(APPEND HEADERS ${CMAKE_CURRENT_LIST_DIR}/Fault.h)
list(APPEND SOURCES ${CMAKE_CURRENT_LIST_DIR}/Fault.cpp)

list(APPEND HEADERS ${CMAKE_CURRENT_LIST_DIR}/Netlist.h)
list(APPEND SOURCES ${CMAKE_CURRENT_LIST_DIR}/Netlist.cpp)

list(APPEND HEADERS ${CMAKE_CURRENT_LIST_DIR}/Faultlist.h)
list(APPEND SOURCES ${CMAKE_CURRENT_LIST_DIR}/Faultlist.cpp)

list(APPEND HEADERS ${CMAKE_CURRENT_LIST_DIR}/Statuslist.h)
list(APPEND SOURCES ${CMAKE_CURRENT_LIST_DIR}/Statuslist.cpp)

list(APPEND HEADERS ${CMAKE_CURRENT_LIST_DIR}/TestCube.h)

list(APPEND HEADERS ${CMAKE_CURRENT_LIST_DIR}/ScanChain.h)
list(APPEND SOURCES ${CMAKE_CURRENT_LIST_DIR}/ScanChain.cpp)

list(APPEND HEADERS ${CMAKE_CURRENT_LIST_DIR}/common.h)

list(APPEND HEADERS ${CMAKE_CURRENT_LIST_DIR}/printers.h)
list(APPEND SOURCES ${CMAKE_CURRENT_LIST_DIR}/printers.cpp)

list(APPEND HEADERS ${CMAKE_CURRENT_LIST_DIR}/Util.h)
list(APPEND SOURCES ${CMAKE_CURRENT_LIST_DIR}/Util.cpp)
