list(APPEND HEADERS ${CMAKE_CURRENT_LIST_DIR}/ContextDefault.h)
list(APPEND HEADERS ${CMAKE_CURRENT_LIST_DIR}/CubeHandler.h)
list(APPEND HEADERS ${CMAKE_CURRENT_LIST_DIR}/CubeHandlerDefault.h)
list(APPEND HEADERS ${CMAKE_CURRENT_LIST_DIR}/CubeHandlerWriteFile.h)
